import * as React from 'react';
import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import Divider from '@mui/material/Divider';
import ListItemText from '@mui/material/ListItemText';
import ListItemAvatar from '@mui/material/ListItemAvatar';
import Avatar from '@mui/material/Avatar';
import Typography from '@mui/material/Typography';
import { BarChart, Bar, Cell, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';
import Box from '@mui/material/Box';
import InputLabel from '@mui/material/InputLabel';
import MenuItem from '@mui/material/MenuItem';
import FormControl from '@mui/material/FormControl';
import Select, { SelectChangeEvent } from '@mui/material/Select';

const abbr2prov = [
  {"abbr": "ah", "full": "安徽"},
  {"abbr": "bj", "full": "北京"},
  {"abbr": "cq", "full": "重庆"},
  {"abbr": "fj", "full": "福建"},
  {"abbr": "gd", "full": "广东"},
  {"abbr": "gs", "full": "甘肃"},
  {"abbr": "gz", "full": "贵州"},
  {"abbr": "gx", "full": "广西"},
  {"abbr": "ha", "full": "河南"},
  {"abbr": "hb", "full": "湖北"},
  {"abbr": "he", "full": "河北"},
  {"abbr": "hi", "full": "海南"},
  {"abbr": "hl", "full": "黑龙江"},
  {"abbr": "hn", "full": "湖南"},
  {"abbr": "jl", "full": "吉林"},
  {"abbr": "js", "full": "江苏"},
  {"abbr": "jx", "full": "江西"},
  {"abbr": "ln", "full": "辽宁"},
  {"abbr": "nm", "full": "内蒙古"},
  {"abbr": "nx", "full": "宁夏"},
  {"abbr": "qh", "full": "青海"},
  {"abbr": "sc", "full": "四川"},
  {"abbr": "sd", "full": "山东"},
  {"abbr": "sh", "full": "上海"},
  {"abbr": "sn", "full": "陕西"},
  {"abbr": "sx", "full": "山西"},
  {"abbr": "tj", "full": "天津"},
  {"abbr": "tw", "full": "台湾"},
  {"abbr": "xj", "full": "新疆"},
  {"abbr": "xz", "full": "西藏"},
  {"abbr": "yn", "full": "云南"},
  {"abbr": "zj", "full": "浙江"},
  {"abbr": "hk", "full": "香港"},
  {"abbr": "mo", "full": "澳门"},
];

const data = [
  {
    name: 'Page A',
    uv: 4000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: 'Page B',
    uv: 3000,
    pv: 1398,
    amt: 2210,
  },
  {
    name: 'Page C',
    uv: 2000,
    pv: 9800,
    amt: 2290,
  },
  {
    name: 'Page D',
    uv: 2780,
    pv: 3908,
    amt: 2000,
  },
  {
    name: 'Page E',
    uv: 1890,
    pv: 4800,
    amt: 2181,
  },
  {
    name: 'Page F',
    uv: 2390,
    pv: 3800,
    amt: 2500,
  },
  {
    name: 'Page G',
    uv: 3490,
    pv: 4300,
    amt: 2100,
  },
];
const DataStat = () => {
  const allProvince = [...new Set(statData.map((stat, idx) => (stat.province)))];

  const [province, setProvince] = React.useState('');
  const [quarterData, setQuarterData] = React.useState([]);

  const [yearlyData, setYearlyData] = React.useState([]);

  const handleChange = (event: SelectChangeEvent) => {
    setProvince(event.target.value as string);
    let tmpQData = statData.filter((stat) => (stat.province === event.target.value));
    setQuarterData(tmpQData);
    const calc = (year : string) => {
      tmpQData.reduce((prev, cur, index, arr) => {
        if(cur.quarter.slice(0, 4) === year){
          return prev + cur.outputValue;
        }
      }, 0)
    };
    
    setYearlyData(
    [{"province": province,"industryType":"AI","quarter":"2019","outputValue":calc("2019")},
    {"province": province,"industryType":"AI","quarter":"2020","outputValue":calc("2020")},
    {"province": province,"industryType":"AI","quarter":"2021","outputValue":calc("2021")}]
    );

  };

  return (
    <>
    <FormControl fullWidth>
      <InputLabel id="select-province-input-label">Province</InputLabel>
      <Select
        labelId="select-province-label"
        id="select-province"
        value={province}
        label="Province"
        onChange={handleChange}
      >
        {allProvince.map((p, idx) => {
          const filtered =abbr2prov.find((t) =>  {
            return t.abbr.toUpperCase() === p.toUpperCase();
          });
          return(
            <MenuItem value={p}>{
              filtered ? filtered.full : p
            }</MenuItem>
            )
        })}

      </Select>
    </FormControl>
    <BarChart width={400} height={250} data={quarterData}>
      <CartesianGrid strokeDasharray="3 3" />
      <XAxis dataKey="quarter" />
      <YAxis />
      <Tooltip /> 
      <Legend />
      <Bar dataKey="outputValue" fill="#8884d8" />
    </BarChart>
    </>
  );
}


const statData = [
  {"province":"AH","industryType":"AI","quarter":"2019Q1","outputValue":4},
  {"province":"AH","industryType":"AI","quarter":"2019Q2","outputValue":5},
  {"province":"AH","industryType":"AI","quarter":"2019Q3","outputValue":6},
  {"province":"AH","industryType":"AI","quarter":"2019Q4","outputValue":7},
  {"province":"AH","industryType":"AI","quarter":"2020Q1","outputValue":9},
  {"province":"AH","industryType":"AI","quarter":"2020Q2","outputValue":9},
  {"province":"AH","industryType":"AI","quarter":"2020Q3","outputValue":10},
  {"province":"AH","industryType":"AI","quarter":"2020Q4","outputValue":11},
  {"province":"AH","industryType":"AI","quarter":"2021Q1","outputValue":12},
  {"province":"AH","industryType":"AI","quarter":"2021Q2","outputValue":13},
  {"province":"AH","industryType":"AI","quarter":"2021Q3","outputValue":14},
  {"province":"AH","industryType":"AI","quarter":"2021Q4","outputValue":15},
  {"province":"BJ","industryType":"AI","quarter":"2019Q1","outputValue":272},
  {"province":"BJ","industryType":"AI","quarter":"2019Q2","outputValue":281},
  {"province":"BJ","industryType":"AI","quarter":"2019Q3","outputValue":292},
  {"province":"BJ","industryType":"AI","quarter":"2019Q4","outputValue":311},
  {"province":"BJ","industryType":"AI","quarter":"2020Q1","outputValue":341},
  {"province":"BJ","industryType":"AI","quarter":"2020Q2","outputValue":383},
  {"province":"BJ","industryType":"AI","quarter":"2020Q3","outputValue":433},
  {"province":"BJ","industryType":"AI","quarter":"2020Q4","outputValue":485},
  {"province":"BJ","industryType":"AI","quarter":"2021Q1","outputValue":550},
  {"province":"BJ","industryType":"AI","quarter":"2021Q2","outputValue":615},
  {"province":"BJ","industryType":"AI","quarter":"2021Q3","outputValue":696},
  {"province":"BJ","industryType":"AI","quarter":"2021Q4","outputValue":789},
  {"province":"CQ","industryType":"AI","quarter":"2019Q1","outputValue":1},
  {"province":"CQ","industryType":"AI","quarter":"2019Q2","outputValue":2},
  {"province":"CQ","industryType":"AI","quarter":"2019Q3","outputValue":2},
  {"province":"CQ","industryType":"AI","quarter":"2019Q4","outputValue":2},
  {"province":"CQ","industryType":"AI","quarter":"2020Q1","outputValue":2},
  {"province":"CQ","industryType":"AI","quarter":"2020Q2","outputValue":2},
  {"province":"CQ","industryType":"AI","quarter":"2020Q3","outputValue":3},
  {"province":"CQ","industryType":"AI","quarter":"2020Q4","outputValue":3},
  {"province":"CQ","industryType":"AI","quarter":"2021Q1","outputValue":3},
  {"province":"CQ","industryType":"AI","quarter":"2021Q2","outputValue":4},
  {"province":"CQ","industryType":"AI","quarter":"2021Q3","outputValue":4},
  {"province":"CQ","industryType":"AI","quarter":"2021Q4","outputValue":4},
  {"province":"FJ","industryType":"AI","quarter":"2019Q1","outputValue":7},
  {"province":"FJ","industryType":"AI","quarter":"2019Q2","outputValue":9},
  {"province":"FJ","industryType":"AI","quarter":"2019Q3","outputValue":11},
  {"province":"FJ","industryType":"AI","quarter":"2019Q4","outputValue":13},
  {"province":"FJ","industryType":"AI","quarter":"2020Q1","outputValue":15},
  {"province":"FJ","industryType":"AI","quarter":"2020Q2","outputValue":17},
  {"province":"FJ","industryType":"AI","quarter":"2020Q3","outputValue":19},
  {"province":"FJ","industryType":"AI","quarter":"2020Q4","outputValue":21},
  {"province":"FJ","industryType":"AI","quarter":"2021Q1","outputValue":23},
  {"province":"FJ","industryType":"AI","quarter":"2021Q2","outputValue":24},
  {"province":"FJ","industryType":"AI","quarter":"2021Q3","outputValue":26},
  {"province":"FJ","industryType":"AI","quarter":"2021Q4","outputValue":28},
  {"province":"GD","industryType":"AI","quarter":"2019Q1","outputValue":130},
  {"province":"GD","industryType":"AI","quarter":"2019Q2","outputValue":136},
  {"province":"GD","industryType":"AI","quarter":"2019Q3","outputValue":144},
  {"province":"GD","industryType":"AI","quarter":"2019Q4","outputValue":153},
  {"province":"GD","industryType":"AI","quarter":"2020Q1","outputValue":165},
  {"province":"GD","industryType":"AI","quarter":"2020Q2","outputValue":185},
  {"province":"GD","industryType":"AI","quarter":"2020Q3","outputValue":216},
  {"province":"GD","industryType":"AI","quarter":"2020Q4","outputValue":244},
  {"province":"GD","industryType":"AI","quarter":"2021Q1","outputValue":270},
  {"province":"GD","industryType":"AI","quarter":"2021Q2","outputValue":320},
  {"province":"GD","industryType":"AI","quarter":"2021Q3","outputValue":354},
  {"province":"GD","industryType":"AI","quarter":"2021Q4","outputValue":394},
  {"province":"GS","industryType":"AI","quarter":"2019Q1","outputValue":0},
  {"province":"GS","industryType":"AI","quarter":"2019Q2","outputValue":0},
  {"province":"GS","industryType":"AI","quarter":"2019Q3","outputValue":0},
  {"province":"GS","industryType":"AI","quarter":"2019Q4","outputValue":0},
  {"province":"GS","industryType":"AI","quarter":"2020Q1","outputValue":0},
  {"province":"GS","industryType":"AI","quarter":"2020Q2","outputValue":0},
  {"province":"GS","industryType":"AI","quarter":"2020Q3","outputValue":0},
  {"province":"GS","industryType":"AI","quarter":"2020Q4","outputValue":0},
  {"province":"GS","industryType":"AI","quarter":"2021Q1","outputValue":0},
  {"province":"GS","industryType":"AI","quarter":"2021Q2","outputValue":0},
  {"province":"GS","industryType":"AI","quarter":"2021Q3","outputValue":0},
  {"province":"GS","industryType":"AI","quarter":"2021Q4","outputValue":0},
  {"province":"GZ","industryType":"AI","quarter":"2019Q1","outputValue":0},
  {"province":"GZ","industryType":"AI","quarter":"2019Q2","outputValue":0},
  {"province":"GZ","industryType":"AI","quarter":"2019Q3","outputValue":0},
  {"province":"GZ","industryType":"AI","quarter":"2019Q4","outputValue":0},
  {"province":"GZ","industryType":"AI","quarter":"2020Q1","outputValue":0},
  {"province":"GZ","industryType":"AI","quarter":"2020Q2","outputValue":0},
  {"province":"GZ","industryType":"AI","quarter":"2020Q3","outputValue":0},
  {"province":"GZ","industryType":"AI","quarter":"2020Q4","outputValue":0},
  {"province":"GZ","industryType":"AI","quarter":"2021Q1","outputValue":0},
  {"province":"GZ","industryType":"AI","quarter":"2021Q2","outputValue":0},
  {"province":"GZ","industryType":"AI","quarter":"2021Q3","outputValue":0},
  {"province":"GZ","industryType":"AI","quarter":"2021Q4","outputValue":0},
  {"province":"GX","industryType":"AI","quarter":"2019Q1","outputValue":0},
  {"province":"GX","industryType":"AI","quarter":"2019Q2","outputValue":0},
  {"province":"GX","industryType":"AI","quarter":"2019Q3","outputValue":0},
  {"province":"GX","industryType":"AI","quarter":"2019Q4","outputValue":0},
  {"province":"GX","industryType":"AI","quarter":"2020Q1","outputValue":0},
  {"province":"GX","industryType":"AI","quarter":"2020Q2","outputValue":0},
  {"province":"GX","industryType":"AI","quarter":"2020Q3","outputValue":0},
  {"province":"GX","industryType":"AI","quarter":"2020Q4","outputValue":0},
  {"province":"GX","industryType":"AI","quarter":"2021Q1","outputValue":0},
  {"province":"GX","industryType":"AI","quarter":"2021Q2","outputValue":0},
  {"province":"GX","industryType":"AI","quarter":"2021Q3","outputValue":1},
  {"province":"GX","industryType":"AI","quarter":"2021Q4","outputValue":1},
  {"province":"HA","industryType":"AI","quarter":"2019Q1","outputValue":4},
  {"province":"HA","industryType":"AI","quarter":"2019Q2","outputValue":5},
  {"province":"HA","industryType":"AI","quarter":"2019Q3","outputValue":6},
  {"province":"HA","industryType":"AI","quarter":"2019Q4","outputValue":7},
  {"province":"HA","industryType":"AI","quarter":"2020Q1","outputValue":9},
  {"province":"HA","industryType":"AI","quarter":"2020Q2","outputValue":9},
  {"province":"HA","industryType":"AI","quarter":"2020Q3","outputValue":10},
  {"province":"HA","industryType":"AI","quarter":"2020Q4","outputValue":11},
  {"province":"HA","industryType":"AI","quarter":"2021Q1","outputValue":13},
  {"province":"HA","industryType":"AI","quarter":"2021Q2","outputValue":13},
  {"province":"HA","industryType":"AI","quarter":"2021Q3","outputValue":14},
  {"province":"HA","industryType":"AI","quarter":"2021Q4","outputValue":15},
  {"province":"HB","industryType":"AI","quarter":"2019Q1","outputValue":10},
  {"province":"HB","industryType":"AI","quarter":"2019Q2","outputValue":13},
  {"province":"HB","industryType":"AI","quarter":"2019Q3","outputValue":16},
  {"province":"HB","industryType":"AI","quarter":"2019Q4","outputValue":19},
  {"province":"HB","industryType":"AI","quarter":"2020Q1","outputValue":24},
  {"province":"HB","industryType":"AI","quarter":"2020Q2","outputValue":27},
  {"province":"HB","industryType":"AI","quarter":"2020Q3","outputValue":30},
  {"province":"HB","industryType":"AI","quarter":"2020Q4","outputValue":32},
  {"province":"HB","industryType":"AI","quarter":"2021Q1","outputValue":35},
  {"province":"HB","industryType":"AI","quarter":"2021Q2","outputValue":39},
  {"province":"HB","industryType":"AI","quarter":"2021Q3","outputValue":42},
  {"province":"HB","industryType":"AI","quarter":"2021Q4","outputValue":46},
  {"province":"HE","industryType":"AI","quarter":"2019Q1","outputValue":8},
  {"province":"HE","industryType":"AI","quarter":"2019Q2","outputValue":10},
  {"province":"HE","industryType":"AI","quarter":"2019Q3","outputValue":12},
  {"province":"HE","industryType":"AI","quarter":"2019Q4","outputValue":14},
  {"province":"HE","industryType":"AI","quarter":"2020Q1","outputValue":17},
  {"province":"HE","industryType":"AI","quarter":"2020Q2","outputValue":18},
  {"province":"HE","industryType":"AI","quarter":"2020Q3","outputValue":20},
  {"province":"HE","industryType":"AI","quarter":"2020Q4","outputValue":22},
  {"province":"HE","industryType":"AI","quarter":"2021Q1","outputValue":24},
  {"province":"HE","industryType":"AI","quarter":"2021Q2","outputValue":25},
  {"province":"HE","industryType":"AI","quarter":"2021Q3","outputValue":27},
  {"province":"HE","industryType":"AI","quarter":"2021Q4","outputValue":29},
  {"province":"HI","industryType":"AI","quarter":"2019Q1","outputValue":0},
  {"province":"HI","industryType":"AI","quarter":"2019Q2","outputValue":0},
  {"province":"HI","industryType":"AI","quarter":"2019Q3","outputValue":0},
  {"province":"HI","industryType":"AI","quarter":"2019Q4","outputValue":0},
  {"province":"HI","industryType":"AI","quarter":"2020Q1","outputValue":0},
  {"province":"HI","industryType":"AI","quarter":"2020Q2","outputValue":0},
  {"province":"HI","industryType":"AI","quarter":"2020Q3","outputValue":0},
  {"province":"HI","industryType":"AI","quarter":"2020Q4","outputValue":0},
  {"province":"HI","industryType":"AI","quarter":"2021Q1","outputValue":0},
  {"province":"HI","industryType":"AI","quarter":"2021Q2","outputValue":0},
  {"province":"HI","industryType":"AI","quarter":"2021Q3","outputValue":0},
  {"province":"HI","industryType":"AI","quarter":"2021Q4","outputValue":1},
  {"province":"HL","industryType":"AI","quarter":"2019Q1","outputValue":0},
  {"province":"HL","industryType":"AI","quarter":"2019Q2","outputValue":0},
  {"province":"HL","industryType":"AI","quarter":"2019Q3","outputValue":0},
  {"province":"HL","industryType":"AI","quarter":"2019Q4","outputValue":0},
  {"province":"HL","industryType":"AI","quarter":"2020Q1","outputValue":0},
  {"province":"HL","industryType":"AI","quarter":"2020Q2","outputValue":0},
  {"province":"HL","industryType":"AI","quarter":"2020Q3","outputValue":0},
  {"province":"HL","industryType":"AI","quarter":"2020Q4","outputValue":0},
  {"province":"HL","industryType":"AI","quarter":"2021Q1","outputValue":0},
  {"province":"HL","industryType":"AI","quarter":"2021Q2","outputValue":0},
  {"province":"HL","industryType":"AI","quarter":"2021Q3","outputValue":0},
  {"province":"HL","industryType":"AI","quarter":"2021Q4","outputValue":1},
  {"province":"HN","industryType":"AI","quarter":"2019Q1","outputValue":0},
  {"province":"HN","industryType":"AI","quarter":"2019Q2","outputValue":0},
  {"province":"HN","industryType":"AI","quarter":"2019Q3","outputValue":0},
  {"province":"HN","industryType":"AI","quarter":"2019Q4","outputValue":0},
  {"province":"HN","industryType":"AI","quarter":"2020Q1","outputValue":0},
  {"province":"HN","industryType":"AI","quarter":"2020Q2","outputValue":0},
  {"province":"HN","industryType":"AI","quarter":"2020Q3","outputValue":0},
  {"province":"HN","industryType":"AI","quarter":"2020Q4","outputValue":1},
  {"province":"HN","industryType":"AI","quarter":"2021Q1","outputValue":1},
  {"province":"HN","industryType":"AI","quarter":"2021Q2","outputValue":1},
  {"province":"HN","industryType":"AI","quarter":"2021Q3","outputValue":1},
  {"province":"HN","industryType":"AI","quarter":"2021Q4","outputValue":1},
  {"province":"JL","industryType":"AI","quarter":"2019Q1","outputValue":0},
  {"province":"JL","industryType":"AI","quarter":"2019Q2","outputValue":0},
  {"province":"JL","industryType":"AI","quarter":"2019Q3","outputValue":0},
  {"province":"JL","industryType":"AI","quarter":"2019Q4","outputValue":0},
  {"province":"JL","industryType":"AI","quarter":"2020Q1","outputValue":0},
  {"province":"JL","industryType":"AI","quarter":"2020Q2","outputValue":0},
  {"province":"JL","industryType":"AI","quarter":"2020Q3","outputValue":0},
  {"province":"JL","industryType":"AI","quarter":"2020Q4","outputValue":0},
  {"province":"JL","industryType":"AI","quarter":"2021Q1","outputValue":0},
  {"province":"JL","industryType":"AI","quarter":"2021Q2","outputValue":1},
  {"province":"JL","industryType":"AI","quarter":"2021Q3","outputValue":1},
  {"province":"JL","industryType":"AI","quarter":"2021Q4","outputValue":1},
  {"province":"JS","industryType":"AI","quarter":"2019Q1","outputValue":24},
  {"province":"JS","industryType":"AI","quarter":"2019Q2","outputValue":28},
  {"province":"JS","industryType":"AI","quarter":"2019Q3","outputValue":32},
  {"province":"JS","industryType":"AI","quarter":"2019Q4","outputValue":39},
  {"province":"JS","industryType":"AI","quarter":"2020Q1","outputValue":45},
  {"province":"JS","industryType":"AI","quarter":"2020Q2","outputValue":50},
  {"province":"JS","industryType":"AI","quarter":"2020Q3","outputValue":54},
  {"province":"JS","industryType":"AI","quarter":"2020Q4","outputValue":57},
  {"province":"JS","industryType":"AI","quarter":"2021Q1","outputValue":60},
  {"province":"JS","industryType":"AI","quarter":"2021Q2","outputValue":64},
  {"province":"JS","industryType":"AI","quarter":"2021Q3","outputValue":70},
  {"province":"JS","industryType":"AI","quarter":"2021Q4","outputValue":79},
  {"province":"JX","industryType":"AI","quarter":"2019Q1","outputValue":0},
  {"province":"JX","industryType":"AI","quarter":"2019Q2","outputValue":0},
  {"province":"JX","industryType":"AI","quarter":"2019Q3","outputValue":0},
  {"province":"JX","industryType":"AI","quarter":"2019Q4","outputValue":0},
  {"province":"JX","industryType":"AI","quarter":"2020Q1","outputValue":0},
  {"province":"JX","industryType":"AI","quarter":"2020Q2","outputValue":0},
  {"province":"JX","industryType":"AI","quarter":"2020Q3","outputValue":0},
  {"province":"JX","industryType":"AI","quarter":"2020Q4","outputValue":1},
  {"province":"JX","industryType":"AI","quarter":"2021Q1","outputValue":1},
  {"province":"JX","industryType":"AI","quarter":"2021Q2","outputValue":1},
  {"province":"JX","industryType":"AI","quarter":"2021Q3","outputValue":1},
  {"province":"JX","industryType":"AI","quarter":"2021Q4","outputValue":1},
  {"province":"LN","industryType":"AI","quarter":"2019Q1","outputValue":4},
  {"province":"LN","industryType":"AI","quarter":"2019Q2","outputValue":5},
  {"province":"LN","industryType":"AI","quarter":"2019Q3","outputValue":6},
  {"province":"LN","industryType":"AI","quarter":"2019Q4","outputValue":7},
  {"province":"LN","industryType":"AI","quarter":"2020Q1","outputValue":8},
  {"province":"LN","industryType":"AI","quarter":"2020Q2","outputValue":9},
  {"province":"LN","industryType":"AI","quarter":"2020Q3","outputValue":11},
  {"province":"LN","industryType":"AI","quarter":"2020Q4","outputValue":12},
  {"province":"LN","industryType":"AI","quarter":"2021Q1","outputValue":13},
  {"province":"LN","industryType":"AI","quarter":"2021Q2","outputValue":13},
  {"province":"LN","industryType":"AI","quarter":"2021Q3","outputValue":14},
  {"province":"LN","industryType":"AI","quarter":"2021Q4","outputValue":15},
  {"province":"NM","industryType":"AI","quarter":"2019Q1","outputValue":0},
  {"province":"NM","industryType":"AI","quarter":"2019Q2","outputValue":0},
  {"province":"NM","industryType":"AI","quarter":"2019Q3","outputValue":0},
  {"province":"NM","industryType":"AI","quarter":"2019Q4","outputValue":0},
  {"province":"NM","industryType":"AI","quarter":"2020Q1","outputValue":0},
  {"province":"NM","industryType":"AI","quarter":"2020Q2","outputValue":0},
  {"province":"NM","industryType":"AI","quarter":"2020Q3","outputValue":0},
  {"province":"NM","industryType":"AI","quarter":"2020Q4","outputValue":0},
  {"province":"NM","industryType":"AI","quarter":"2021Q1","outputValue":0},
  {"province":"NM","industryType":"AI","quarter":"2021Q2","outputValue":0},
  {"province":"NM","industryType":"AI","quarter":"2021Q3","outputValue":0},
  {"province":"NM","industryType":"AI","quarter":"2021Q4","outputValue":0},
  {"province":"NX","industryType":"AI","quarter":"2019Q1","outputValue":0},
  {"province":"NX","industryType":"AI","quarter":"2019Q2","outputValue":0},
  {"province":"NX","industryType":"AI","quarter":"2019Q3","outputValue":0},
  {"province":"NX","industryType":"AI","quarter":"2019Q4","outputValue":0},
  {"province":"NX","industryType":"AI","quarter":"2020Q1","outputValue":0},
  {"province":"NX","industryType":"AI","quarter":"2020Q2","outputValue":0},
  {"province":"NX","industryType":"AI","quarter":"2020Q3","outputValue":0},
  {"province":"NX","industryType":"AI","quarter":"2020Q4","outputValue":0},
  {"province":"NX","industryType":"AI","quarter":"2021Q1","outputValue":0},
  {"province":"NX","industryType":"AI","quarter":"2021Q2","outputValue":0},
  {"province":"NX","industryType":"AI","quarter":"2021Q3","outputValue":0},
  {"province":"NX","industryType":"AI","quarter":"2021Q4","outputValue":0},
  {"province":"QH","industryType":"AI","quarter":"2019Q1","outputValue":0},
  {"province":"QH","industryType":"AI","quarter":"2019Q2","outputValue":0},
  {"province":"QH","industryType":"AI","quarter":"2019Q3","outputValue":0},
  {"province":"QH","industryType":"AI","quarter":"2019Q4","outputValue":0},
  {"province":"QH","industryType":"AI","quarter":"2020Q1","outputValue":0},
  {"province":"QH","industryType":"AI","quarter":"2020Q2","outputValue":0},
  {"province":"QH","industryType":"AI","quarter":"2020Q3","outputValue":0},
  {"province":"QH","industryType":"AI","quarter":"2020Q4","outputValue":0},
  {"province":"QH","industryType":"AI","quarter":"2021Q1","outputValue":0},
  {"province":"QH","industryType":"AI","quarter":"2021Q2","outputValue":0},
  {"province":"QH","industryType":"AI","quarter":"2021Q3","outputValue":0},
  {"province":"QH","industryType":"AI","quarter":"2021Q4","outputValue":0},
  {"province":"SC","industryType":"AI","quarter":"2019Q1","outputValue":19},
  {"province":"SC","industryType":"AI","quarter":"2019Q2","outputValue":23},
  {"province":"SC","industryType":"AI","quarter":"2019Q3","outputValue":27},
  {"province":"SC","industryType":"AI","quarter":"2019Q4","outputValue":24},
  {"province":"SC","industryType":"AI","quarter":"2020Q1","outputValue":40},
  {"province":"SC","industryType":"AI","quarter":"2020Q2","outputValue":45},
  {"province":"SC","industryType":"AI","quarter":"2020Q3","outputValue":49},
  {"province":"SC","industryType":"AI","quarter":"2020Q4","outputValue":53},
  {"province":"SC","industryType":"AI","quarter":"2021Q1","outputValue":55},
  {"province":"SC","industryType":"AI","quarter":"2021Q2","outputValue":59},
  {"province":"SC","industryType":"AI","quarter":"2021Q3","outputValue":65},
  {"province":"SC","industryType":"AI","quarter":"2021Q4","outputValue":74},
  {"province":"SD","industryType":"AI","quarter":"2019Q1","outputValue":4},
  {"province":"SD","industryType":"AI","quarter":"2019Q2","outputValue":5},
  {"province":"SD","industryType":"AI","quarter":"2019Q3","outputValue":6},
  {"province":"SD","industryType":"AI","quarter":"2019Q4","outputValue":7},
  {"province":"SD","industryType":"AI","quarter":"2020Q1","outputValue":8},
  {"province":"SD","industryType":"AI","quarter":"2020Q2","outputValue":9},
  {"province":"SD","industryType":"AI","quarter":"2020Q3","outputValue":10},
  {"province":"SD","industryType":"AI","quarter":"2020Q4","outputValue":11},
  {"province":"SD","industryType":"AI","quarter":"2021Q1","outputValue":12},
  {"province":"SD","industryType":"AI","quarter":"2021Q2","outputValue":13},
  {"province":"SD","industryType":"AI","quarter":"2021Q3","outputValue":14},
  {"province":"SD","industryType":"AI","quarter":"2021Q4","outputValue":15},
  {"province":"SH","industryType":"AI","quarter":"2019Q1","outputValue":140},
  {"province":"SH","industryType":"AI","quarter":"2019Q2","outputValue":146},
  {"province":"SH","industryType":"AI","quarter":"2019Q3","outputValue":154},
  {"province":"SH","industryType":"AI","quarter":"2019Q4","outputValue":163},
  {"province":"SH","industryType":"AI","quarter":"2020Q1","outputValue":175},
  {"province":"SH","industryType":"AI","quarter":"2020Q2","outputValue":195},
  {"province":"SH","industryType":"AI","quarter":"2020Q3","outputValue":226},
  {"province":"SH","industryType":"AI","quarter":"2020Q4","outputValue":254},
  {"province":"SH","industryType":"AI","quarter":"2021Q1","outputValue":280},
  {"province":"SH","industryType":"AI","quarter":"2021Q2","outputValue":334},
  {"province":"SH","industryType":"AI","quarter":"2021Q3","outputValue":370},
  {"province":"SH","industryType":"AI","quarter":"2021Q4","outputValue":411},
  {"province":"SN","industryType":"AI","quarter":"2019Q1","outputValue":5},
  {"province":"SN","industryType":"AI","quarter":"2019Q2","outputValue":7},
  {"province":"SN","industryType":"AI","quarter":"2019Q3","outputValue":9},
  {"province":"SN","industryType":"AI","quarter":"2019Q4","outputValue":12},
  {"province":"SN","industryType":"AI","quarter":"2020Q1","outputValue":14},
  {"province":"SN","industryType":"AI","quarter":"2020Q2","outputValue":16},
  {"province":"SN","industryType":"AI","quarter":"2020Q3","outputValue":18},
  {"province":"SN","industryType":"AI","quarter":"2020Q4","outputValue":20},
  {"province":"SN","industryType":"AI","quarter":"2021Q1","outputValue":22},
  {"province":"SN","industryType":"AI","quarter":"2021Q2","outputValue":24},
  {"province":"SN","industryType":"AI","quarter":"2021Q3","outputValue":26},
  {"province":"SN","industryType":"AI","quarter":"2021Q4","outputValue":27},
  {"province":"SX","industryType":"AI","quarter":"2019Q1","outputValue":0},
  {"province":"SX","industryType":"AI","quarter":"2019Q2","outputValue":0},
  {"province":"SX","industryType":"AI","quarter":"2019Q3","outputValue":0},
  {"province":"SX","industryType":"AI","quarter":"2019Q4","outputValue":0},
  {"province":"SX","industryType":"AI","quarter":"2020Q1","outputValue":0},
  {"province":"SX","industryType":"AI","quarter":"2020Q2","outputValue":0},
  {"province":"SX","industryType":"AI","quarter":"2020Q3","outputValue":0},
  {"province":"SX","industryType":"AI","quarter":"2020Q4","outputValue":0},
  {"province":"SX","industryType":"AI","quarter":"2021Q1","outputValue":0},
  {"province":"SX","industryType":"AI","quarter":"2021Q2","outputValue":0},
  {"province":"SX","industryType":"AI","quarter":"2021Q3","outputValue":0},
  {"province":"SX","industryType":"AI","quarter":"2021Q4","outputValue":1},
  {"province":"TJ","industryType":"AI","quarter":"2019Q1","outputValue":8},
  {"province":"TJ","industryType":"AI","quarter":"2019Q2","outputValue":10},
  {"province":"TJ","industryType":"AI","quarter":"2019Q3","outputValue":12},
  {"province":"TJ","industryType":"AI","quarter":"2019Q4","outputValue":15},
  {"province":"TJ","industryType":"AI","quarter":"2020Q1","outputValue":17},
  {"province":"TJ","industryType":"AI","quarter":"2020Q2","outputValue":19},
  {"province":"TJ","industryType":"AI","quarter":"2020Q3","outputValue":21},
  {"province":"TJ","industryType":"AI","quarter":"2020Q4","outputValue":24},
  {"province":"TJ","industryType":"AI","quarter":"2021Q1","outputValue":26},
  {"province":"TJ","industryType":"AI","quarter":"2021Q2","outputValue":28},
  {"province":"TJ","industryType":"AI","quarter":"2021Q3","outputValue":30},
  {"province":"TJ","industryType":"AI","quarter":"2021Q4","outputValue":31},
  {"province":"TW","industryType":"AI","quarter":"2019Q1","outputValue":0},
  {"province":"TW","industryType":"AI","quarter":"2019Q2","outputValue":0},
  {"province":"TW","industryType":"AI","quarter":"2019Q3","outputValue":0},
  {"province":"TW","industryType":"AI","quarter":"2019Q4","outputValue":0},
  {"province":"TW","industryType":"AI","quarter":"2020Q1","outputValue":0},
  {"province":"TW","industryType":"AI","quarter":"2020Q2","outputValue":0},
  {"province":"TW","industryType":"AI","quarter":"2020Q3","outputValue":0},
  {"province":"TW","industryType":"AI","quarter":"2020Q4","outputValue":0},
  {"province":"TW","industryType":"AI","quarter":"2021Q1","outputValue":0},
  {"province":"TW","industryType":"AI","quarter":"2021Q2","outputValue":0},
  {"province":"TW","industryType":"AI","quarter":"2021Q3","outputValue":1},
  {"province":"TW","industryType":"AI","quarter":"2021Q4","outputValue":1},
  {"province":"XJ","industryType":"AI","quarter":"2019Q1","outputValue":0},
  {"province":"XJ","industryType":"AI","quarter":"2019Q2","outputValue":0},
  {"province":"XJ","industryType":"AI","quarter":"2019Q3","outputValue":0},
  {"province":"XJ","industryType":"AI","quarter":"2019Q4","outputValue":0},
  {"province":"XJ","industryType":"AI","quarter":"2020Q1","outputValue":0},
  {"province":"XJ","industryType":"AI","quarter":"2020Q2","outputValue":0},
  {"province":"XJ","industryType":"AI","quarter":"2020Q3","outputValue":0},
  {"province":"XJ","industryType":"AI","quarter":"2020Q4","outputValue":0},
  {"province":"XJ","industryType":"AI","quarter":"2021Q1","outputValue":0},
  {"province":"XJ","industryType":"AI","quarter":"2021Q2","outputValue":0},
  {"province":"XJ","industryType":"AI","quarter":"2021Q3","outputValue":0},
  {"province":"XJ","industryType":"AI","quarter":"2021Q4","outputValue":0},
  {"province":"XZ","industryType":"AI","quarter":"2019Q1","outputValue":0},
  {"province":"XZ","industryType":"AI","quarter":"2019Q2","outputValue":0},
  {"province":"XZ","industryType":"AI","quarter":"2019Q3","outputValue":0},
  {"province":"XZ","industryType":"AI","quarter":"2019Q4","outputValue":0},
  {"province":"XZ","industryType":"AI","quarter":"2020Q1","outputValue":0},
  {"province":"XZ","industryType":"AI","quarter":"2020Q2","outputValue":0},
  {"province":"XZ","industryType":"AI","quarter":"2020Q3","outputValue":0},
  {"province":"XZ","industryType":"AI","quarter":"2020Q4","outputValue":0},
  {"province":"XZ","industryType":"AI","quarter":"2021Q1","outputValue":0},
  {"province":"XZ","industryType":"AI","quarter":"2021Q2","outputValue":0},
  {"province":"XZ","industryType":"AI","quarter":"2021Q3","outputValue":0},
  {"province":"XZ","industryType":"AI","quarter":"2021Q4","outputValue":0},
  {"province":"YN","industryType":"AI","quarter":"2019Q1","outputValue":0},
  {"province":"YN","industryType":"AI","quarter":"2019Q2","outputValue":0},
  {"province":"YN","industryType":"AI","quarter":"2019Q3","outputValue":0},
  {"province":"YN","industryType":"AI","quarter":"2019Q4","outputValue":0},
  {"province":"YN","industryType":"AI","quarter":"2020Q1","outputValue":0},
  {"province":"YN","industryType":"AI","quarter":"2020Q2","outputValue":0},
  {"province":"YN","industryType":"AI","quarter":"2020Q3","outputValue":0},
  {"province":"YN","industryType":"AI","quarter":"2020Q4","outputValue":0},
  {"province":"YN","industryType":"AI","quarter":"2021Q1","outputValue":0},
  {"province":"YN","industryType":"AI","quarter":"2021Q2","outputValue":0},
  {"province":"YN","industryType":"AI","quarter":"2021Q3","outputValue":0},
  {"province":"YN","industryType":"AI","quarter":"2021Q4","outputValue":0},
  {"province":"ZJ","industryType":"AI","quarter":"2019Q1","outputValue":140},
  {"province":"ZJ","industryType":"AI","quarter":"2019Q2","outputValue":146},
  {"province":"ZJ","industryType":"AI","quarter":"2019Q3","outputValue":154},
  {"province":"ZJ","industryType":"AI","quarter":"2019Q4","outputValue":163},
  {"province":"ZJ","industryType":"AI","quarter":"2020Q1","outputValue":175},
  {"province":"ZJ","industryType":"AI","quarter":"2020Q2","outputValue":195},
  {"province":"ZJ","industryType":"AI","quarter":"2020Q3","outputValue":226},
  {"province":"ZJ","industryType":"AI","quarter":"2020Q4","outputValue":254},
  {"province":"ZJ","industryType":"AI","quarter":"2021Q1","outputValue":280},
  {"province":"ZJ","industryType":"AI","quarter":"2021Q2","outputValue":334},
  {"province":"ZJ","industryType":"AI","quarter":"2021Q3","outputValue":370},
  {"province":"ZJ","industryType":"AI","quarter":"2021Q4","outputValue":411},
  {"province":"HK","industryType":"AI","quarter":"2019Q1","outputValue":1},
  {"province":"HK","industryType":"AI","quarter":"2019Q2","outputValue":2},
  {"province":"HK","industryType":"AI","quarter":"2019Q3","outputValue":2},
  {"province":"HK","industryType":"AI","quarter":"2019Q4","outputValue":2},
  {"province":"HK","industryType":"AI","quarter":"2020Q1","outputValue":2},
  {"province":"HK","industryType":"AI","quarter":"2020Q2","outputValue":2},
  {"province":"HK","industryType":"AI","quarter":"2020Q3","outputValue":3},
  {"province":"HK","industryType":"AI","quarter":"2020Q4","outputValue":3},
  {"province":"HK","industryType":"AI","quarter":"2021Q1","outputValue":3},
  {"province":"HK","industryType":"AI","quarter":"2021Q2","outputValue":4},
  {"province":"HK","industryType":"AI","quarter":"2021Q3","outputValue":4},
  {"province":"HK","industryType":"AI","quarter":"2021Q4","outputValue":4},
  {"province":"MO","industryType":"AI","quarter":"2019Q1","outputValue":0},
  {"province":"MO","industryType":"AI","quarter":"2019Q2","outputValue":0},
  {"province":"MO","industryType":"AI","quarter":"2019Q3","outputValue":0},
  {"province":"MO","industryType":"AI","quarter":"2019Q4","outputValue":0},
  {"province":"MO","industryType":"AI","quarter":"2020Q1","outputValue":0},
  {"province":"MO","industryType":"AI","quarter":"2020Q2","outputValue":0},
  {"province":"MO","industryType":"AI","quarter":"2020Q3","outputValue":1},
  {"province":"MO","industryType":"AI","quarter":"2020Q4","outputValue":0},
  {"province":"MO","industryType":"AI","quarter":"2021Q1","outputValue":1},
  {"province":"MO","industryType":"AI","quarter":"2021Q2","outputValue":1},
  {"province":"MO","industryType":"AI","quarter":"2021Q3","outputValue":1},
  {"province":"MO","industryType":"AI","quarter":"2021Q4","outputValue":1}
];

export default DataStat;